### ISSUE TITLE
Can't login on workspace

### ISSUE THREAD

**Issue by neurolabs** [RocketChat/Rocket.Chat.ReactNative#2533]
### Description:

I'm trying to log into our workspace (self-hosted instance). I can enter the workspace URL, but when I then  enter username and password and press the sign in button, nothing happens.
I tried resetting the apps storage, does not help.

### Environment Information:

- Rocket.Chat Server Version: 3.7.0
- Rocket.Chat App Version: 4.11.0.2137
- Device Name: Nubia Z17 Mini
- OS Version: Lineageos 9

### Steps to reproduce:

1. Choose ~'Select a workspace'
2. enter the workspace URL
3. press ~'connect'
4. press ~'login'
5. enter username and password
6. press ~'login'

### Expected behavior:

I am logged in and can access chats.

### Actual behavior:

~'login' button flashes once, but otherwise nothing happens. The login screen stays visible, I can press ~'login' again. No error messages.

**Comment by diegolmello** [comment]
@neurolabs Can you uninstall and try again?

**Comment by neurolabs** [comment]
Uninstalled, reinstalled, deleted app data and cache, tried again, to no avail

**Comment by diegolmello** [comment]
We need more info from your side then.
This is a basic feature and it works.
Try on https://open.rocket.chat.

**Comment by Jheysoon** [comment]
I can't also login in app and in https://open.rocket.chat/

I try logging in via Github and have a console `{"isClientSafe":true,"message":"[undefined]","errorType":"Meteor.Error"}`

**Comment by neurolabs** [comment]
@diegolmello tried on https://open.rocket.chat, does not work either. Both (open.rocket.chat and our own workspace) work in the browser.
On our instance I don't see anything in the server logs (docker-compose setup).

What else can I do to help you validate this issue?

**Comment by diegolmello** [comment]
If you can't login on our `open` server, it might be something on your end (device or network).
As you can imagine, this is our server and we (and tons of other people) use it everyday.
Can you debug it and check what's going on?

**Comment by neurolabs** [comment]
On my device, the app has worked previously, but stopped working (not allowing to log in). No updates of the device's software in between.
I've tried different networks (mobile, wifi), no difference.

I've tried on another device (same wifi), login works on that one. The first notable difference is that on the ~"your workspace" screen (before the login form), my device does not show the logo and name of the workspace/server, only the url. On the other device, the logo and name are shown.

Could you please provide me with more concrete testing instructions?

**Comment by diegolmello** [comment]
Follow `How to run` until you're able to inspect the app.

**Comment by haxpak** [comment]
Same here,
trying to build the app.
No white labelling applied, just added own google-services.json file

trying to connect to open.rocket.chat

```
git clone

yarn

npm start 

yarn android

```


getting error

```
 ERROR    Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `ForwardRef(_c)`, expected `object`.
    in ForwardRef(_c) (at TextInput.js:154)
    in RCTextInput (at ServerInput/index.js:44)
    in RCTView (at View.js:34)
    in View (at ServerInput/index.js:43)
    in ServerInput (at NewServerView/index.js:348)
    in RCTView (at View.js:34)
    in View (at FormContainer.js:21)
    in FormContainerInner (at NewServerView/index.js:346)
    in RNCSafeAreaView (at SafeAreaView.js:16)
    in _c (at FormContainer.js:41)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at FormContainer.js:35)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at KeyboardAwareHOC.js:487)
    in KeyboardAwareScrollView (at KeyboardView.js:24)
    in KeyboardView (at FormContainer.js:29)
    in FormContainer (at NewServerView/index.js:341)
    in NewServerView (at theme.js:9)
    in ThemedComponent (created by ConnectFunction)
    in ConnectFunction (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at OutsideStack.js:28)
    in _OutsideStack (created by ConnectFunction)
    in ConnectFunction (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:70)
    in MaybeScreen (at CardStack.tsx:545)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at OutsideStack.js:86)
    in OutsideStackModal (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at AppContainer.js:66)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:376)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at AppContainer.js:54)
    in Unknown (created by ConnectFunction)
    in ConnectFunction (at app/index.js:201)
    in ForwardRef
    in ForwardRef (at Provider.js:37)
    in Unknown (at app/index.js:200)
    in Provider (at app/index.js:184)
    in RCTView (at View.js:34)
    in View (at NativeAppearance.tsx:4)
    in FallbackAppearanceProvider (at src/index.tsx:70)
    in AppearanceProvider (at app/index.js:183)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at app/index.js:182)
    in Root (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Thu Oct 22 2020 17:39:02.106]  ERROR    Warning: Failed prop type: Invalid prop `fontSize` of type `number` supplied to `Button`, expected `string`.
    in Button (at LoginView.js:178)
    in LoginView (at theme.js:9)
    in ThemedComponent (created by ConnectFunction)
    in ConnectFunction (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at OutsideStack.js:28)
    in _OutsideStack (created by ConnectFunction)
    in ConnectFunction (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:70)
    in MaybeScreen (at CardStack.tsx:545)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at OutsideStack.js:86)
    in OutsideStackModal (at SceneView.tsx:112)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:105)
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at AppContainer.js:66)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:376)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at AppContainer.js:54)
    in Unknown (created by ConnectFunction)
    in ConnectFunction (at app/index.js:201)
    in ForwardRef
    in ForwardRef (at Provider.js:37)
    in Unknown (at app/index.js:200)
    in Provider (at app/index.js:184)
    in RCTView (at View.js:34)
    in View (at NativeAppearance.tsx:4)
    in FallbackAppearanceProvider (at src/index.tsx:70)
    in AppearanceProvider (at app/index.js:183)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at app/index.js:182)
    in Root (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Thu Oct 22 2020 17:44:08.319]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:11.292]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:21.167]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:27.419]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:33.732]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:43.866]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:43.905]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:44:53.502]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:00.153]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:06.290]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:16.428]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:16.521]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:26.406]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:32.603]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:38.857]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:48.806]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:48.838]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:45:58.817]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:46:04.988]  ERROR    [RangeError: Maximum call stack size exceeded]
[Thu Oct 22 2020 17:46:11.118]  ERROR    [RangeError: Maximum call stack size exceeded]
 ERROR    [RangeError: Maximum call stack size exceeded]
```

**Comment by mmggmmgg** [comment]
+1 
I have the same problem too. Clicking the login button. The button blinks once, but the login does not occur and there are no logs on the server. Reinstalled, cleaned the cache.
Installing the same apk on a new phone for the first time works. The difference is in the absence of an icon and a bold name for the server.

**Comment by mmggmmgg** [comment]
I found all folders and files of this apk and deleted them. But I don't have root. What are the ways to clean the file system? Does android have an analogue of the MS registry?

**Comment by neurolabs** [comment]
@diegolmello When debugging, I basically see the same thing as @haxpak . First error 

```
 ERROR    Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `ForwardRef(_c)`, expected `object`.
```

happens before accessing the ~"your workspace" screen that is missing the icon and server name. The other error

```
ERROR    Warning: Failed prop type: Invalid prop `fontSize` of type `number` supplied to `Button`, expected `string`.
```

happens on the login screen after the ~"your workspace" screen.

So it seems that there is no logging happening directly with first symptoms.

Does this help? What else can I do?

**Comment by mmggmmgg** [comment]
Это автоответчик. 
Я проверяю этот почтовый ящик один раз в неделю. Для большей оперативности используйте 1@romango.ru

Михаил Городилов

**Comment by neurolabs** [comment]
@mmggmmgg you really should disable your auto reply!

**Comment by diegolmello** [comment]
These aren't errors, but PropTypes warnings.

`[RangeError: Maximum call stack size exceeded]` can be anything on your end.
Search on StackOverflow.

**Comment by neurolabs** [comment]
@diegolmello 
Can I do anything else? What other options do we have for gathering more information?
Now that a couple of people experience the same thing, how are you going to handle the issue?

**Comment by mmggmmgg** [comment]
Hi guys. I have a workaround. So, I have two identical android 10 smartphones (let it be A and B). I have several different APKs. One of the APKs is in debug mode.
I install all APKs on my smartphone A except the one in debug mode. And I install several APKs on smartphone B, including the one in debug mode. As a result, on smartphone B, I get the bug described in this ticket. Smartphone A continues to perform well. Thus, the bug appears only with different installations of the APK, but one of the APK must be in debug mode.

**Comment by phriedrich** [comment]
I had the same problem last weekend with a friend who got a new Android phone. 

After installing the Rocket.Chat app from the Google Play App Store they weren't able to log in, as described above. 

What helped in this case, was tap-and-hold on the app's icon, select "app info", and then in the dialog was a point "data and caches". From there I was able to clear them. After that I re-opened the app and then was able to login.

**Comment by neurolabs** [comment]
@phriedrich For me, your approach does not work, as mentioned in the original bug report and comment https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2533#issuecomment-705790401

**Comment by AmatorPhasma** [comment]
I have a handful of users with the same problem (Android 9/10) in the last two weeks, 
I noticed also that after entering the workspace (our server or open.rocket.chat) not even the logo is loaded in the next screen.

**Comment by neurolabs** [comment]
@diegolmello this is not fixed for me in 4.12.0.2140. Please reopen this issue.

I deleted cache and app data before trying to log in.

**Comment by diegolmello** [comment]
@neurolabs That PR removes `AllowBackup` manifest attribute, which is stored on device's OS when the app is uninstalled.
Can you uninstall and try again?

**Comment by neurolabs** [comment]
@diegolmello uninstalling, reinstalling did not help either.

Anything else I can try?

**Comment by xlinuxmanx** [comment]
I have this issue as well. I have tried older versions of the Android app as well and it simply does not login. I left the logs open while logging into the mobile app and it shows this post message when i press "Login"

`I20201130-01:13:26.030(0) API ➔ debug POST: /api/v1/login`

I will then spam the Login button until i finally get the error "Your credentials were rejected! Please try again"

And when that happens, i get this message in the logs:

`I20201130-01:14:34.393(0) API ➔ debug post login threw an error: Error: Error, too many requests. Please slow down. You must wait 58 seconds before trying this endpoint again. [error-too-many-requests]     at APIClass.enforceRateLimit (app/api/server/api.js:232:10)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:371:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 `

Now, when i login through the website, i get this POST message instead:

`I20201130-01:16:10.782(0) API ➔ debug POST: /api/v1/method.callAnon/login`

Notice that the POST directory is different for the long on web to Android. Is this a bug? seems like people with Android 9/10 are having this issue. Hope this can help

**Comment by diegolmello** [comment]
@xlinuxmanx If you spam requests, the server will always respond with `Too many requests`.

> Notice that the POST directory is different for the long on web to Android

They are the same. `method.callAnon/*` is a helper to make DDP calls to be ran using HTTP protocol.

> seems like people with Android 9/10 are having this issue.

I have Android 10 here and it's working.
If you can debug the app on your device, it's going to help us a lot.

**Comment by neurolabs** [comment]
@diegolmello see above comments from @haxpak and myself for debugging output.

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2533#issuecomment-716492861

**Comment by neurolabs** [comment]
I see the error, I can debug. I tried, did not get any errors. Feel free to tell me what to do in order to help you.

**Comment by diegolmello** [comment]
Can you reach me at https://open.rocket.chat?
I can't think on anything else than a quick call.
Thanks.

**Comment by neurolabs** [comment]
@diegolmello and me agreed that I will try to drill down on this with a `git bisect`, because it had been working on my phone in the past. This might take me a couple of days/weeks.

**Comment by xlinuxmanx** [comment]
Hey everyone. I was able to fix my issue with Apache. in my case, the issue was that i forgot to enable one of the PHP modules called "proxy_wstunnel". After i enabled that module and restarted Apache, i was able to connect with the mobile app.

So just make sure, if you're using apache for reverse proxy, that you have ran all of these commands:
```
a2enmod proxy_http
a2enmod proxy
a2enmod ssl
a2enmod proxy_wstunnel
a2enmod rewrite
```

**Comment by C1ean** [comment]
Very strange, but I also had a similar problem on 4.13.1
In this case, on the emulator I run like this:
```
yarn
npx pod-install
yarn ios
```
it is not reproduced.

On the device, after creating the archive and distribute ipa - the problem still exists, and after installing the application, the login to the workspace does not work - the button does not respond to any input data.
I think this is an build problem, it does not depend on the device (tried it on 3 different ones)
But app from appstore is work correct

The problem appeared after 4.10. + Version.  (last work version 4.7.)

I can't understand what's going on.
https://user-images.githubusercontent.com/3279295/104205920-01d04a80-5440-11eb-9678-76f142f48c12.mp4

**Comment by C1ean** [comment]
Another very strange is that when bulid app Debug on the device, there is no problem. 
If I get Release option while run, the problem is reproduced immediately.
What is the fundamental difference in the build of these two options?

**Comment by C1ean** [comment]
Any news? @neurolabs  did you solve this issue?

**Comment by neurolabs** [comment]
@C1ean No, sorry, I am currently too busy to invest time. The issue still persists for me, though.

**Comment by C1ean** [comment]
@neurolabs  thanks, I hope @diegolmello maybe clears something up ..

**Comment by diegolmello** [comment]
> But app from appstore is work correct

@C1ean This issue is not related to whitelabel.
The author of the issue can join his server, but can't login using the app for the store.
Open a new issue to get help.
Thanks.

**Comment by amoebav** [comment]
I'm having the same issue on v4.14. I enter in my workspace url and then tap connect, but nothing happens.

**Comment by erikvanberkum** [comment]
We have one iPhone currently unable to login, all other iPhones work fine. When trying to log in it keeps hanging on SSO tap which turns black and never disappears, When closing the screen x left top, than it returns to the login page. 

Delete and reinstall app no success
We can log in to the server via a safari or brave browsers on the particular iPhone.

We are running the app version 4.29.0.34197 on a RocketChat 4.8.1 server
