### ISSUE TITLE
Cannot read property 'FDROID_BUILD' of null

### ISSUE THREAD

**Issue by Scorpio92** [RocketChat/Rocket.Chat.ReactNative#2614]
### Description:

I try to build whitelabel app from single-server branch.
Current actual commit is 5e633e550e23fdf4e1a618f1e47caba63eb10660.
If I set property APPLICATIONID in gradle.properties, app stay on spash screen and not react. In logcat I see:

```
2020-11-06 17:18:58.352 28099-28229/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'FDROID_BUILD' of null, js engine: hermes, stack:
    anonymous@1:680415
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:637854
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:616917
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:610093
    v@1:87485
    d@1:87135
    o@1:86804
    anonymous@1:94206
    h@1:483899
    run@1:484231
    runApplication@1:484804
    value@1:118292
    anonymous@1:116794
    value@1:117764
    value@1:116752
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:235)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2020-11-06 17:18:58.352 28099-28229/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'FDROID_BUILD' of null, js engine: hermes, stack:
    anonymous@1:680415
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:637854
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:616917
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:610093
    v@1:87485
    d@1:87135
    o@1:86804
    anonymous@1:94206
    h@1:483899
    run@1:484231
    runApplication@1:484804
    value@1:118292
    anonymous@1:116794
    value@1:117764
    value@1:116752
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:235)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2020-11-06 17:18:58.352 28099-28229/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: ru.vostbank.itchat, PID: 28099
    com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'FDROID_BUILD' of null, js engine: hermes, stack:
    anonymous@1:680415
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:637854
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:616917
    v@1:87485
    d@1:87178
    o@1:86804
    anonymous@1:610093
    v@1:87485
    d@1:87135
    o@1:86804
    anonymous@1:94206
    h@1:483899
    run@1:484231
    runApplication@1:484804
    value@1:118292
    anonymous@1:116794
    value@1:117764
    value@1:116752
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:235)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

If I use chat.rocket.reactnative for application id, It's works.

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: last from singe-server branch, commit 5e633e550e23fdf4e1a618f1e47caba63eb10660
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. switch to **singe-server** branch
2. change **APPLICATIONID** in gradle.properties and build **play** release
3. run

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2548
