### ISSUE TITLE
Error uploading files File size (size = 0) is too small (min = 1) [file-too-small]

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#2852]
### Description:

Some files (Word, Excel, MP3 we have tested) are not loaded from the Android application. On our rocket server there are no extension restrictions for uploading files. From the web interface and the desktop application we have tried to load the same documents and we have not had problems, only from the mobile app.
According to the records, the file has size = 0 and at least it must be = 1 but this has no relation to the actual size of the files that we are trying to upload.

### Environment Information:

- Rocket.Chat Server Version: 3.10.5
- Rocket.Chat App Version: 4.14.0.22702
- Device Name: ---
- OS Version: ---

### Steps to reproduce:

1. 
2. 
3. 

### Actual behavior:

![Screenshot_20210127-172317_RocketChat](https://user-images.githubusercontent.com/35962168/106371114-aa324a00-632e-11eb-9cab-be8996751323.jpg)

### Additional context:

```
I20210130-17:51:05.434(-5) server.js:204 API ➔ debug POST: /api/v1/rooms.upload/GNGoo5iBf6dTjGyggdieWKCepwPyB7ppuh 
I20210130-17:51:05.435(-5) canAccessRoom {   id: 'zkTd9Hjb96bg9ZcCA',   clientAddress: 'IPADDRESS',   httpHeaders: {     connection: 'upgrade',     host: 'myhostname',     'x-real-ip': 'IPADDRESS',     'x-forward-for': 'IPADDRESS, IPADDRESS',     'x-forward-proto': 'http',     'x-nginx-proxy': 'true',     'content-length': '214',     'x-forwarded-for': 'IPADDRESS',     'user-agent': 'RC Mobile; android 8.0.0; v4.14.0 (22702)',     'x-user-id': 'dieWKCepwPyB7ppuh',     'x-auth-token': '3LJ2G_gjRYYCmsdgZd7AgUKW2gd7rRsClnykKRZQj5e',     'content-type': 'multipart/form-data; boundary=RNFetchBlob-aq30w5oo3ob8q5ldue1edo',     'accept-encoding': 'gzip'   },   userId: 'dieWKCepwPyB7ppuh' } 
I20210130-17:51:05.436(-5) server.js:204 Meteor ➔ method canAccessRoom -> userId: dieWKCepwPyB7ppuh, arguments: ["GNGoo5iBf6dTjGyggdieWKCepwPyB7ppuh","dieWKCepwPyB7ppuh"] 
I20210130-17:51:05.445(-5) server.js:204 API ➔ debug post rooms.upload/:rid threw an error: Error: File size (size = 0) is too small (min = 1) [file-too-small]     at Object.fileTooSmallError (packages/jalik:ufs/ufs-filter.js:42:50)     at Filter.check (packages/jalik:ufs/ufs-filter.js:88:25)     at FileUploadClass.insert (app/file-upload/server/lib/FileUpload.js:591:11)     at FileUploadClass.insertSync (packages/meteor.js:306:21)     at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/rooms.js:124:35)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at Object.post (app/api/server/v1/rooms.js:122:27)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20210130-17:51:05.446(-5) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: {     success: false,     error: 'File size (size = 0) is too small (min = 1) [file-too-small]',     stack: undefined,     errorType: 'file-too-small'   } }

```

**Comment by aleadco** [comment]
The two files shown in the error image have a weight of 53Kb and 21.87Kb respectively.

**Comment by aleadco** [comment]
The issue was resolved with update https://github.com/RocketChat/Rocket.Chat/releases/tag/3.11.0
I will leave it open for a few days to review in depth.
