### ISSUE TITLE
no space between custom emojis

### ISSUE THREAD

**Issue by saurabhkanswal** [RocketChat/Rocket.Chat.ReactNative#2887]
->there is no space between custom emojis
![customEmoji](https://user-images.githubusercontent.com/26677033/107364254-37c92300-6b01-11eb-8d07-eef4327fbcdb.jpeg)

**Comment by saurabhkanswal** [comment]
Working on the issue:)

**Comment by saurabhkanswal** [comment]
@diegolmello  before I commit any changes to my local-branch, the last test case is falling. although I have updated the snapshots by using the `yarn test -u` command.


PASS app/lib/database/utils.test.js (5.393s)                                                                                                                                                     PASS app/utils/shortnameToUnicode/shortnameToUnicode.test.js                                                                                                                                     PASS app/presentation/UnreadBadge/getUnreadStyle.test.js                                                                                                                                         PASS app/utils/base64-js/base64-js.test.js (9.202s)                                                                                                                                              FAIL __tests__/Storyshots.test.js                                                                                                                                                                  ● Test suite failed to run                                                                                                                                                                                                                                                                                                                                                                          TypeError: Cannot read property 'path' of undefined                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   at Object. (app/utils/appGroup.js:162:90)                                                                                                                                             at Object. (app/lib/database/index.js:1349:91)                                                                                                                                        at Object. (app/containers/Avatar/index.js:2170:91)                                                                                                                                   at Object. (app/presentation/RoomItem/Wrapper.js:319:88)
--
