### ISSUE TITLE
Running npm install - snyk error

### ISSUE THREAD

**Issue by markmadlangbayan** [RocketChat/Rocket.Chat.ReactNative#355]
- latest commit on `develop` branch is `1faf9bf`
- node: v9.4.0
- npm: 6.1.0
- Steps to reproduce:
`npm install`

Error:
```
> npm run snyk-protect; exit 0


> rocket-chat-reactnative@0.0.1 snyk-protect .../Rocket.Chat.ReactNative
> snyk protect

An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 413
    at .../Rocket.Chat.ReactNative/node_modules/snyk/lib/snyk-test/npm/index.js:127:23
    at .../Rocket.Chat.ReactNative/node_modules/snyk/lib/request/index.js:12:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rocket-chat-reactnative@0.0.1 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rocket-chat-reactnative@0.0.1 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     {Users}/.npm/_logs/2018-07-11T16_08_04_668Z-debug.log
added 2418 packages from 1569 contributors and audited 150311 packages in 119.29s
found 218 vulnerabilities (23 low, 159 moderate, 36 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

- debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '.../v9.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'snyk-protect' ]
2 info using npm@6.1.0
3 info using node@v9.4.0
4 verbose run-script [ 'presnyk-protect', 'snyk-protect', 'postsnyk-protect' ]
5 info lifecycle rocket-chat-reactnative@0.0.1~presnyk-protect: rocket-chat-reactnative@0.0.1
6 info lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: rocket-chat-reactnative@0.0.1
7 verbose lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: unsafe-perm in lifecycle true
8 verbose lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:.../Rocket.Chat.ReactNative/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:.../Rocket.Chat.ReactNative/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:{Users}/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:~/.fastlane/bin:{Users}/Library/Android/sdk/platform-tools:{Users}/Library/Android/sdk/tools:{Users}/Library/Android/sdk/emulator:{Users}/Library/Android/sdk/tools:{Users}/Library/Android/sdk/platform-tools:{Users}/.rvm/gems/ruby-2.3.1/bin:{Users}/.rvm/gems/ruby-2.3.1@global/bin:{Users}/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:{Users}/anaconda3/bin:~/.fastlane/bin:{Users}/Library/Android/sdk/platform-tools:{Users}/Library/Android/sdk/tools:{Users}/Library/Android/sdk/emulator:{Users}/.rvm/gems/ruby-2.3.1/bin:{Users}/.rvm/gems/ruby-2.3.1@global/bin:{Users}/.rvm/rubies/ruby-2.3.1/bin:{Users}/.rvm/bin:{Users}/Documents/tools:{Users}/Library/Android/sdk//build-tools/27.0.3:{Users}/.rvm/bin:{Users}/Documents/tools:{Users}/.rvm/bin:{Users}/Library/Android/sdk//build-tools/27.0.3
9 verbose lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: CWD: .../Rocket.Chat.ReactNative
10 silly lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: Args: [ '-c', 'snyk protect' ]
11 silly lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: Returned: code: 1  signal: null
12 info lifecycle rocket-chat-reactnative@0.0.1~snyk-protect: Failed to exec snyk-protect script
13 verbose stack Error: rocket-chat-reactnative@0.0.1 snyk-protect: `snyk protect`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid rocket-chat-reactnative@0.0.1
15 verbose cwd .../Rocket.Chat.ReactNative
16 verbose Darwin 17.5.0
17 verbose argv ".../v9.4.0/bin/node" "/usr/local/bin/npm" "run" "snyk-protect"
18 verbose node v9.4.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error rocket-chat-reactnative@0.0.1 snyk-protect: `snyk protect`
22 error Exit status 1
23 error Failed at the rocket-chat-reactnative@0.0.1 snyk-protect script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by markmadlangbayan** [comment]
Awesome, that worked. Thanks!
