### ISSUE TITLE
Script is missing on develop branch

### ISSUE THREAD

**Issue by irepan** [RocketChat/Rocket.Chat.ReactNative#424]
When I try to do npm install it throws up an error, seems that there is one script missing under scripts folder

```
Error: Command failed: /.../Rocket.Chat.ReactNative/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (/.../Rocket.Chat.ReactNative/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@8.1.4 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the detox@8.1.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Volumes/Macintosh HD2/Users/irepan/.npm/_logs/2018-09-03T15_23_07_359Z-debug.log

```

And if I run the command with the error, I get this:

```
Mac-mini-Nivel-7:New.Rocket.Chat.ReactNative irepan$ node scripts/postinstall.js
module.js:538
    throw err;
    ^

Error: Cannot find module '/.../Rocket.Chat.ReactNative/scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by diegolmello** [comment]
@irepan The error says detox lib couldn't find that script.
This is something on your environment.
Check detox github issues like this: https://github.com/wix/Detox/issues/627

**Comment by irepan** [comment]
Isn’t that script part of the Project/scripts folder? 

 

De: Diego Mello <notifications@github.com>
Responder a: "RocketChat/Rocket.Chat.ReactNative" <reply@reply.github.com>
Fecha: lunes, 3 de septiembre de 2018, 10:54
Para: "RocketChat/Rocket.Chat.ReactNative" <Rocket.Chat.ReactNative@noreply.github.com>
CC: irepan <irepitan@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [RocketChat/Rocket.Chat.ReactNative] Script is missing on develop branch (#424)

 

@irepan The error says detox lib couldn't find that script.
This is something on your environment.
Check detox github issues like this: wix/Detox#627
