### ISSUE TITLE
crash when I start RocketChat app

### ISSUE THREAD

**Issue by seconp** [RocketChat/Rocket.Chat.ReactNative#4799]
### Description:
crash when I start the app.
### Environment Information:

- Rocket.Chat Server Version: I use your open channel--https://open.rocket.chat
- Rocket.Chat App Version:I use latest version building app--4.34.0
- Device Name: Android--xiaomi
- OS Version: Android 11

### Steps to reproduce:
1. download [latest version](https://github.com/RocketChat/Rocket.Chat.ReactNative)
2. follow [the guide](https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/android-app-white-labelling) to build the apk.(By the way, I use mac building apk. Why am I successful with `npx react-native run-android --main-activity chat.rocket.reactnative.MainActivity --variant=ExperimentalFossRelease --appId Rocketer.Chat`, but failed with other variant, for example: `npx react-native run-android --main-activity chat.rocket.reactnative.MainActivity --variant=experimentalPlayDebug --appId Rocketer.Chat`?)
3. then install the app and touch the icon to start it.
### Expected behavior:
It starts normally and displays screen.
### Actual behavior:
First time I touch the icon, the app crashes. If I click the icon again, it can start successfully. It means that I had to tap the icon twice to successfully start the app. After I exit the app, I still have to repeat the above two steps to successfully start it.
### Additional context:
I recorded a [video](https://github.com/seconp/forQuestion/blob/main/tapTwiceToStartApp.mp4) recording the bug.

I use command `adb logcat > logcat.log` to catch error log, get the [result](https://github.com/seconp/forQuestion/blob/main/logcat.log): The following log is shown starting at line 87709 in [logcat.log](https://github.com/seconp/forQuestion/blob/main/logcat.log)
```js
01-09 18:54:47.259 12089 12499 W RecentsModel: getRunningTask   taskInfo=TaskInfo{userId=0 pcFlags:0 stackId=2593 taskId=2593 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=chat.rocket.reactnative/.MainActivity } baseActivity=ComponentInfo{chat.rocket.reactnative/chat.rocket.reactnative.MainActivity} topActivity=ComponentInfo{chat.rocket.reactnative/chat.rocket.reactnative.MainActivity} origActivity=null realActivity=ComponentInfo{chat.rocket.reactnative/chat.rocket.reactnative.MainActivity} numActivities=1 lastActiveTime=166040329 supportsSplitScreenMultiWindow=true resizeMode=1 isResizeable=true token=android.window.WindowContainerToken@20ccc9c topActivityType=1 pictureInPictureParams=null topActivityInfo=ActivityInfo{272d6a5 chat.rocket.reactnative.MainActivity}
01-09 18:54:47.259 12089 12499 W RecentsModel: getTaskInfoIgnoreHomeAndFreeform   taskInfo=ComponentInfo{chat.rocket.reactnative/chat.rocket.reactnative.MainActivity}
01-09 18:54:47.260  5298 28667 I SCTaskStackListener: onTaskStackChanged! inSplit = false
01-09 18:54:47.260  5229  5229 W FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
01-09 18:54:47.260 12089 12499 E ActivityManagerWrapper: get all recent tasks force including 2593
01-09 18:54:47.261  5229  5229 D SoLoader: libjscexecutor.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.261  5229  5229 D SoLoader: libjscexecutor.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.261 12089 12499 E ActivityManagerWrapper: getRecentTasks: size=5
01-09 18:54:47.261  5229  5229 D SoLoader: libjscexecutor.so not found on /system/lib64
01-09 18:54:47.261 12089 12499 E ActivityManagerWrapper: getRecentTasks: taskId=2593   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=chat.rocket.reactnative/.MainActivity }
01-09 18:54:47.261 12089 12499 E ActivityManagerWrapper: getRecentTasks: taskId=2587   userId=0   baseIntent=Intent { flg=0x10800000 cmp=com.android.settings/.Settings$UsbDetailsActivity }
01-09 18:54:47.261 12089 12499 E ActivityManagerWrapper: getRecentTasks: taskId=2585   userId=0   baseIntent=Intent { act=miui.intent.action.CHECK_ACCESS_CONTROL flg=0x18800000 pkg=com.miui.securitycenter cmp=com.miui.securitycenter/com.miui.applicationlock.ConfirmAccessControl }
01-09 18:54:47.261  5229  5229 D SoLoader: libjscexecutor.so not found on /vendor/lib64
01-09 18:54:47.261 12089 12499 E ActivityManagerWrapper: getRecentTasks: taskId=2565   userId=0   baseIntent=Intent { act=android.intent.action.VIEW dat=content://com.alibaba.android.rimet.file.provider/file/DingTalk/app-experimental-foss-release(1).apk flg=0x12800000 cmp=com.miui.packageinstaller/com.miui.packageInstaller.NewPackageInstallerActivity }
01-09 18:54:47.261 12089 12499 E ActivityManagerWrapper: getRecentTasks: taskId=2530   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flg=0x10840000 cmp=com.android.incallui/.InCallActivity }
01-09 18:54:47.261  5229  5229 E SoLoader: couldn't find DSO to load: libjscexecutor.so
01-09 18:54:47.261  5229  5229 E SoLoader: 	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64 flags = 0]
01-09 18:54:47.261  5229  5229 E SoLoader: 	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a]
01-09 18:54:47.261  5229  5229 E SoLoader: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
01-09 18:54:47.261  5229  5229 E SoLoader: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
01-09 18:54:47.261  5229  5229 E SoLoader: 	Native lib dir: /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.261  5229  5229 E SoLoader:  result: 0
01-09 18:54:47.261  5229  5229 D SoLoader: libhermes.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.263  5229  5229 D SoLoader: liblog.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.263  5229  5229 D SoLoader: liblog.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.263  5229  5229 D SoLoader: liblog.so found on /system/lib64
01-09 18:54:47.263  5229  5229 D SoLoader: liblog.so loaded implicitly
01-09 18:54:47.263  5229  5229 D SoLoader: libm.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.263  5229  5229 D SoLoader: libm.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.263  5229  5229 D SoLoader: libm.so found on /system/lib64
01-09 18:54:47.263  5229  5229 D SoLoader: libm.so loaded implicitly
01-09 18:54:47.263  5229  5229 D SoLoader: libdl.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.263  5229  5229 D SoLoader: libdl.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.263  5229  5229 D SoLoader: libdl.so found on /system/lib64
01-09 18:54:47.263  5229  5229 D SoLoader: libdl.so loaded implicitly
01-09 18:54:47.263  5229  5229 D SoLoader: libc.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.263  5229  5229 D SoLoader: libc.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.263  5229  5229 D SoLoader: libc.so found on /system/lib64
01-09 18:54:47.263  5229  5229 D SoLoader: libc.so loaded implicitly
01-09 18:54:47.265  5229  5229 D SoLoader: libhermes.so found on DirectAPKSoSource: 4
01-09 18:54:47.265  5229  5229 D SoLoader: libhermes-executor-debug.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.265 12089 12105 D LifecycleResourceManager: begin check cache... 
01-09 18:54:47.265  5229  5229 D SoLoader: libhermes-executor-debug.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.265  5229  5229 D SoLoader: libhermes-executor-debug.so not found on /system/lib64
01-09 18:54:47.265  5229  5229 D SoLoader: libhermes-executor-debug.so not found on /vendor/lib64
01-09 18:54:47.265  5229  5229 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so
01-09 18:54:47.265  5229  5229 E SoLoader: 	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64 flags = 0]
01-09 18:54:47.265  5229  5229 E SoLoader: 	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a]
01-09 18:54:47.265  5229  5229 E SoLoader: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
01-09 18:54:47.265  5229  5229 E SoLoader: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
01-09 18:54:47.265  5229  5229 E SoLoader: 	Native lib dir: /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.265  5229  5229 E SoLoader:  result: 0
01-09 18:54:47.265  5229  5229 D SoLoader: libhermes-executor-release.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.267  1067  1138 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.268  1067  1138 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.269  2552  2673 D ImageWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
01-09 18:54:47.269 12089 12105 W System  : A resource failed to call release. 
01-09 18:54:47.270 12089 12105 I chatty  : uid=10106(com.miui.home) FinalizerDaemon identical 1 line
01-09 18:54:47.270 12089 12105 W System  : A resource failed to call release. 
01-09 18:54:47.270 12089 12117 D StatusBarController: handleMessage: flag 800000  disable false
01-09 18:54:47.270 12089 12089 D Launcher_WallpaperUtils: changeStatusBarMode:false
01-09 18:54:47.272 12089 12105 W System  : A resource failed to call release. 
01-09 18:54:47.272  5229  5229 D SoLoader: libhermes-executor-release.so found on DirectAPKSoSource: 4
01-09 18:54:47.284  1067  1138 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.285  1067  1699 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.286  2552  2673 D ImageWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
01-09 18:54:47.287  1671  1671 D CompatibilityInfo: mCompatibilityFlags - 0
01-09 18:54:47.287  1671  1671 D CompatibilityInfo: applicationDensity - 560
01-09 18:54:47.287  1671  1671 D CompatibilityInfo: applicationScale - 1.0
01-09 18:54:47.289  1067  1699 W DisplayIdentification: Invalid EDID: falling back to serial number due to missing display name.
01-09 18:54:47.289  1067  1699 W DisplayIdentification: Invalid EDID: falling back to ASCII text due to missing serial number.
01-09 18:54:47.293  1671  1683 W System  : A resource failed to call release. 
01-09 18:54:47.293  1671  1683 I chatty  : uid=1000(system) FinalizerDaemon identical 2 lines
01-09 18:54:47.293  1671  1683 W System  : A resource failed to call release. 
01-09 18:54:47.293  1671  1683 W System  : A resource failed to call close. 
01-09 18:54:47.299  5229  5229 D View    : chat.rocket.reactnative initForcedUseForceDark: 1
01-09 18:54:47.300  1067  1699 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.301  1067  1699 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.302  2552  2673 D ImageWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
01-09 18:54:47.313  5229  5261 D SoLoader: libfbjni.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.314  5229  5261 D SoLoader: libandroid.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/lib/arm64
01-09 18:54:47.314  5229  5261 D SoLoader: libandroid.so not found on /data/app/~~MSYth7TzAwaXrLVlUyftJQ==/chat.rocket.reactnative-7bkP8UYf6Br8769W4QVUqA==/base.apk!/lib/arm64-v8a
01-09 18:54:47.314  5229  5261 D SoLoader: libandroid.so found on /system/lib64
01-09 18:54:47.314  5229  5261 D SoLoader: libandroid.so loaded implicitly
01-09 18:54:47.315  5229  5261 D SoLoader: libfbjni.so found on DirectAPKSoSource: 4
01-09 18:54:47.317  1067  1699 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.317  1067  1138 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.318  2552  2673 D ImageWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
01-09 18:54:47.318 12089 13637 W FloatingIconLayer: release
01-09 18:54:47.323  5229  5261 V AsyncStorageExpoMigration: No scoped database found
01-09 18:54:47.326  5229  5261 I TetheringManager: registerTetheringEventCallback:chat.rocket.reactnative
01-09 18:54:47.326 12089 12089 D RecentsImpl: mActivityStateObserver chat.rocket.reactnative.MainActivity
01-09 18:54:47.326 12089 12089 W RecentsImpl: onResumed className=chat.rocket.reactnative.MainActivity   mIsInAnotherPro=false   isKeyguardLocked=false
01-09 18:54:47.327 12089 12126 D RecentsImpl: showNavStubView
01-09 18:54:47.327 12089 12126 D NavStubView_Touch: setKeepHidden    old=false   new=false
01-09 18:54:47.327 12089 12125 W RecentsImpl: disableTouchBySwipeStatusBar    disable=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: disableTouchBySwipeStatusBar    old=false   new=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: disableTouchBySwipeStatusBar    old=false   new=false
01-09 18:54:47.327 12089 12125 W RecentsImpl: disableBackStubWindow    disableTouch=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: disableTouch    old=true   new=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: updateTouchable    old=true   new=true
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: disableTouch    old=true   new=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: updateTouchable    old=true   new=true
01-09 18:54:47.327 12089 12125 D RecentsImpl: showBackStubWindow  hasNavigationBar=true
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: setKeepHidden    old=true   new=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch: updateTouchable    old=true   new=false
01-09 18:54:47.327 12089 12125 D GestureStubView_Touch:   updateTouchable---requestApplyInsets
01-09 18:54:47.327 12089 12125 W GestureStubView: adaptRotation   currentRotation=0   mRotation=0
01-09 18:54:47.328 12089 12125 D GestureStubView: resetRenderProperty: showGestureStub
01-09 18:54:47.328 12089 12125 D GestureStubView_Touch: disableTouch    old=false   new=false
01-09 18:54:47.328 12089 12125 D GestureStubView: showGestureStub
01-09 18:54:47.328 12089 12125 D GestureStubView_Touch: setKeepHidden    old=true   new=false
01-09 18:54:47.328 12089 12125 D GestureStubView_Touch: updateTouchable    old=true   new=false
01-09 18:54:47.328 12089 12125 D GestureStubView_Touch:   updateTouchable---requestApplyInsets
01-09 18:54:47.328 12089 12125 W GestureStubView: adaptRotation   currentRotation=0   mRotation=0
01-09 18:54:47.328 12089 12125 D GestureStubView: resetRenderProperty: showGestureStub
01-09 18:54:47.328 12089 12125 D GestureStubView_Touch: disableTouch    old=false   new=false
01-09 18:54:47.328 12089 12125 D GestureStubView: showGestureStub
01-09 18:54:47.330  5229  5258 D ViewContentFactory: initViewContentFetcherClass
01-09 18:54:47.330  5229  5258 D ViewContentFactory: getInterceptorPackageInfo
01-09 18:54:47.331  5229  5258 D ViewContentFactory: getInitialApplication took 0ms
01-09 18:54:47.331  5229  5258 D ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
01-09 18:54:47.334  1067  1138 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.335  5229  5258 D ViewContentFactory: initViewContentFetcherClass took 4ms
01-09 18:54:47.335  5229  5258 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
01-09 18:54:47.335  5229  5258 D ViewContentFactory: createInterceptor took 4ms
01-09 18:54:47.335  1067  1138 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.337  2552  2673 D ImageWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: QUALCOMM build                   : c91de61166, Ibd0298713c
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Build Date                       : 03/01/21
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.04
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Local Branch                     : 
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Remote Branch                    : 
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Remote Branch                    : 
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Reconstruct Branch               : 
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
01-09 18:54:47.344  5229  5255 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-09 18:54:47.345 12089 12125 D GestureStubView: gatherTransparentRegion: need render w:54  h:1920
01-09 18:54:47.347  5229  5255 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
01-09 18:54:47.345  5229  5229 W chat.rocket.reactnative: type=1400 audit(0.0:571837): avc: denied { write } for comm=4173796E635461736B202331 name="tasks" dev="cgroup" ino=21 scontext=u:r:untrusted_app:s0:c127,c257,c512,c768 tcontext=u:object_r:cgroup:s0 tclass=file permissive=0 app=chat.rocket.reactnative
01-09 18:54:47.351  1067  1699 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.352  1067  1699 W SurfaceFlinger: eEarlyWakeup is deprecated. Use eExplicitEarlyWakeup[Start|End]
01-09 18:54:47.352 12089 12125 D GestureStubView: gatherTransparentRegion: need render w:54  h:1920
01-09 18:54:47.353  2552  2673 D ImageWallpaperRenderer: OFFSET  x: 1.0  y: 0.0
01-09 18:54:47.354  5229  5264 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
01-09 18:54:47.354  5229  5264 E AndroidRuntime: Process: chat.rocket.reactnative, PID: 5229
01-09 18:54:47.354  5229  5264 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process chat.rocket.reactnative. Make sure to call FirebaseApp.initializeApp(Context) first.
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@21.1.0:1)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.refreshToken(FcmToken.java:75)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.onAppReady(FcmToken.java:65)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleWork(FcmInstanceIdRefreshHandlerService.java:26)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-09 18:54:47.354  5229  5264 E AndroidRuntime: 	... 3 more
```

**Comment by diegolmello** [comment]
You're running two very different builds, but the error is related to Firebase, apparently.
