### ISSUE TITLE
Android app crashes when opening any channel/DM

### ISSUE THREAD

**Issue by a-0-dev** [RocketChat/Rocket.Chat.ReactNative#5211]
### Description:

Since updating to the latest RocketChat version available in FDroid, opening any direct message or channel crashes the app. Reinstallation, deleting cache and storage and force-closing the app did not help.

### Environment Information:

- Rocket.Chat Server Version: 6.3
- Rocket.Chat App Version: 4.40.0.47251
- Device Name: Shift Phone 6mq
- OS Version: Android 13 / CalyxOS 4.12.0

### Steps to reproduce:

1. Update the app from FDroid
2. Open RocketChat
3. Try to open a channel/DM and see that the app closes

### Expected behavior:

Correctly open the channel/DM

### Actual behavior:

App closes immediately, user sees the home screen of the phone

**Comment by diegolmello** [comment]
Can you take and share with us a bug report? https://developer.android.com/studio/debug/bug-report
Since it's F-Droid, we don't track anything. Not even bugs.
Thanks!

**Comment by Me4Linux** [comment]
I'm experienceing exactly the same behaviour of the client. The only difference in my setup is that I'm using a Google Pixel 6a with GrapheneOS 2023090600 (Android 13).

**Comment by Me4Linux** [comment]
Here's what I get:


```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230805.001/2023090600:user/release-keys
package: chat.rocket.android:47251
process: chat.rocket.android
processUptime: 3223 + 192 ms
installer: com.android.packageinstaller

com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'Type' of undefined, js engine: hermes, stack:
anonymous@1:4399226
loadModuleImplementation@1:129350
guardedLoadModule@1:128898
metroRequire@1:128526
anonymous@1:4397013
loadModuleImplementation@1:129350
guardedLoadModule@1:128855
metroRequire@1:128526
useVideoConf@1:4386278
HeaderCallButton@1:4737781
renderWithHooks@1:200082
beginWork$1@1:239681
performUnitOfWork@1:225815
workLoopSync@1:225672
renderRootSync@1:225556
performSyncWorkOnRoot@1:222914
flushSyncCallbacks@1:190306
batchedUpdatesImpl@1:240076
batchedUpdates@1:183100
_receiveRootNodeIDEvent@1:183378
receiveEvent@1:233998
__callFunction@1:167235
anonymous@1:165719
__guard@1:166679
callFunctionReturnFlushedQueue@1:165677

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by GleidsonDaniel** [comment]
@Me4Linux @a-0-dev 
Did you have the video calling functionality activated?

**Comment by a-0-dev** [comment]
@GleidsonDaniel it's deactivated server-side for me

**Comment by shilin-da** [comment]
Same issue for me on client 4.40 and server 3.8.8. Downgraded client to 4.38.

> Did you have the video calling functionality activated?

Yes, we do have https://meet.jit.si/ enabled on server side

**Comment by GleidsonDaniel** [comment]
Guys the error only occurs in the Fdroid build available in stores, the official build of the app it works normally, and running the foss variant built locally works normally too (The variant that the Fdroid team use to build the app), probably It's the same error that happened a while ago with pushs, Fdroid team has a script to remove parts of the code, perhaps an update to the code broke this script, so it's necessary Fdroid team update the script.

In the error report that @Me4Linux sent we can see the source of the error `useVideoConf`, but as I said, without the code removal that occurs, the app works normally.

**Comment by GleidsonDaniel** [comment]
@linsui do you know what needs to be updated for the build to work?
Or who can I talk to so that the build can be corrected?

**Comment by shilin-da** [comment]
Thanks, @GleidsonDaniel, it looks like there is already an open issue in their tracker: https://gitlab.com/fdroid/fdroiddata/-/issues/3076

**Comment by Me4Linux** [comment]
Just found an open bug report for that issue:
https://gitlab.com/fdroid/fdroiddata/-/issues/3076

**Comment by GleidsonDaniel** [comment]
I looked at the issue and it is exactly the same problem that occurred previously.
As they already have an issue open and are tracking the error, I will close the issue here, given that the problem is not in our app but in the F-droid build script.
