### ISSUE TITLE
IndexOutOfBoundsException immediately after submitting message

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5261]
### Description:

Under certain circumstances, the Android app crashes immediately after submitting a message.

### Environment Information:

- Rocket.Chat Server Version: 6.4.0
- Rocket.Chat App Version: 4.41.0.49563
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

Unfortunately, I don't know the preconditions for the problem to occur. However, in case it is occur to submit a single message to observe an app crash.

I will add further informations to this bug report in case I'm able to determine the preconditions for this problem to occur.

### Expected behavior:

The app does not crash.

### Actual behavior:

The app crashes. An `IndexOutOfBoundsException` can be found in the device log.

### Additional context:

The stack trace of the exception:

```
10-08 12:38:25.887  8724  8724 E AndroidRuntime: FATAL EXCEPTION: main
10-08 12:38:25.887  8724  8724 E AndroidRuntime: Process: chat.rocket.android, PID: 8724
10-08 12:38:25.887  8724  8724 E AndroidRuntime: java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 2 (child count is 2)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2194)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4383)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.draw(View.java:22002)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20859)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:583)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4317)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4125)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3385)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by diegolmello** [comment]
Hey @paulchen.
Let us know if you find it.
I'm seeing this error on logs, but I can't reproduce it.
Thanks!
