### ISSUE TITLE
App crashes when entering specific channel with Trying to add a 'RCTVirtualText' to a 'RCTView'

### ISSUE THREAD

**Issue by wolfff** [RocketChat/Rocket.Chat.ReactNative#672]
- Your Rocket.Chat Experimental app version: 1.10.0 (Android Store beta channel)
- Your Rocket.Chat server version: current ubuntu Snap
- Device (or Simulator) you're running with: Samsung S9

On my company's (internal) rocket chat the app crashes when entering one specific channel (which could be browsed in web client without any issues.
The android app crahses with:
`AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTVirtualText' to a 'RCTView')
`
Please let me know how I could assist debugging.

**Comment by diegolmello** [comment]
Hi, @wolfff.
Thanks for opening this issue.
There’s two ways: if it’s ok for you, you can send me a test user to that channel or you can debug it yourself trying to find out which message is different from the others.

**Comment by justnero** [comment]
Hi, @diegolmello 
I would like to raise this issue once again. I've made some research and it seems like markdown list causes it. Tested using these devices:

**Android:**
Rocket.Chat app version: 4.6.4.2118
Rocket.Chat Experimental app version: 4.6.4.16459
Rocket.Chat server version: 3.0.3 (docker)
Device you're running with: Samsung S8+

**iOS:**
Rocket.Chat app version: 4.6.4.295
Rocket.Chat server version: 3.0.3 (docker)
Device you're running with: iPhone 7+

On an Android device opening a chat will crash the app, on an iPhone the list just won't render and app remain working.

Here is the log I've got using `adb logcat`:
```
05-02 16:11:37.439  7976  8183 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-02 16:11:37.439  7976  8183 E AndroidRuntime: Process: chat.rocket.android, PID: 7976
05-02 16:11:37.439  7976  8183 E AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a '[RCTVirtualText 3419]' to a '[RCTView 3423]')
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:220)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:53)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:437)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:540)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
05-02 16:11:37.439  7976  8183 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

I've also identified the message that is causing it:
```json
{
    "_id": "RzDgsbetBtgAtpFYp",
    "_updatedAt": "2020-05-14T12:14:24.650Z",
    "alias": "App name",
    "avatar": "/avatar/app.name",
    "blocks": [
        {
            "appId": "0daddca7-4290-43da-a1a9-900309d21c19",
            "blockId": "6774e801-95dc-11ea-bd67-03ff1ea0e4c7",
            "text": {
                "text": "*List:*\n1. Item",
                "type": "mrkdwn"
            },
            "type": "section"
        }
    ],
    "channels": [
    ],
    "editedAt": "2020-05-14T12:14:24.647Z",
    "editedBy": {
        "_id": "3u9jTet57GvxMSxmK",
        "username": "app.name"
    },
    "groupable": false,
    "mentions": [
    ],
    "msg": "",
    "rid": "LPyJg7FkZF4XLgpFj",
    "ts": "2020-05-14T12:14:04.936Z",
    "u": {
        "_id": "3u9jTet57GvxMSxmK",
        "name": "App name",
        "username": "app.name"
    },
    "urls": [
    ]
}
```
If I remove `1.` from `$.blocks[0].text.text` it would work well.
