### ISSUE TITLE
react-native link throwing error

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat.ReactNative#807]
rnpm-install ERR! Something went wrong while linking. Error: Maximum call stack size exceeded 
Please file an issue here: https://github.com/facebook/react-native/issues 

Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1883:25)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/node_modules/xcode/lib/parser/pbxproj.js:1888:24)

it is working till 2019ec58cecceb049d5a06afd0887002fab153aa commit

**Comment by diegolmello** [comment]
@pranavpandey1998official Why did you ran `link` without installing anything new? I'm closing this for now.

**Comment by pranavpandey1998official** [comment]
@diegolmello I was installing react native tabview.. I have to make pr for that with head detched response this
