### ISSUE TITLE
Open URL doesn't work on Android 9

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#877]
Fabric points to CustomTabsAndroid.openURL.
It seems we need to require FLAG_ACTIVITY_NEW_TASK flag.
We should do something like this: https://github.com/droibit/react-native-custom-tabs/blob/develop/android/src/main/java/com/github/droibit/android/reactnative/customtabs/CustomTabsModule.java#L181

Here's the stack error from Fabric.
```
Fatal Exception: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ContextImpl.startActivity(ContextImpl.java:974)
       at android.app.ContextImpl.startActivity(ContextImpl.java:950)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
       at chat.rocket.reactnative.CustomTabsAndroid.openURL(CustomTabsAndroid.java:49)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by lolimay** [comment]
<img src="https://user-images.githubusercontent.com/32427260/58000282-e433cc00-7b0a-11e9-81d4-76d9860cd5a1.gif" height="500" />

Sorry, I can not reproduce this bug on Android 9. Did you mean opening URL with custom chrome tabs?

**Comment by diegolmello** [comment]
@lolimay That's odd, but it doesn't mean it's not happening.
This is the second most recurring error on Fabric.

**Comment by lolimay** [comment]
> @lolimay That's odd, but it doesn't mean it's not happening.
> This is the second most recurring error on Fabric.

OK, I will try to reproduce it.

**Comment by weijia-yu** [comment]
any chance it is `http`? Since Android banned `http` on Android 9
